CREATE TABLE users(NAME VARCHAR(10), EMAIL VARCHAR(30), PASS CHAR(32), PRIMARY KEY(NAME));
CREATE INDEX index_email ON users (EMAIL);
CREATE TABLE items(ID INT NOT NULL AUTO_INCREMENT, IMGURL VARCHAR(255), TITLE VARCHAR(500), SOURCE VARCHAR(50), LINK VARCHAR(255), PRIMARY KEY(ID), UNIQUE(IMGURL));
CREATE INDEX index_url ON items (IMGURL);
CREATE TABLE comments(ID INT NOT NULL AUTO_INCREMENT, ITEM INT NOT NULL, DATE DATETIME, TEXT VARCHAR(140), AUTHOR VARCHAR(10), LIKES INT, PRIMARY KEY(ID), FOREIGN KEY (AUTHOR) REFERENCES users(NAME), FOREIGN KEY (ITEM) REFERENCES items(ID));
CREATE TABLE temp_tokens(TOKEN CHAR(32), NAME VARCHAR(10), EMAIL VARCHAR(30), PASS CHAR(32), EXP DATETIME, PRIMARY KEY(TOKEN), UNIQUE(EMAIL));
CREATE TABLE access_tokens(TOKEN CHAR(32), NAME VARCHAR(10), EXP DATETIME, PRIMARY KEY(TOKEN), FOREIGN KEY (NAME) REFERENCES users(NAME));
CREATE TABLE likes (USER VARCHAR(10) NOT NULL, COMMENT INT NOT NULL, PRIMARY KEY(USER, COMMENT), FOREIGN KEY(USER) REFERENCES users(NAME), FOREIGN KEY(COMMENT) REFERENCES comments(ID));